id: I384896EB
legacy_id: P000309
ocr_import_info:
  bdrc_scan_id: W1KG14505
  source: bdrc
  ocr_info:
    timestamp: '2020-03-12T14:26:08'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T05:02:27.394918+00:00'
last_modified: 2022-08-27 13:04:26.067888
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG14505
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG14505
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། དགེ་འདུན་གྲུབ།
  author: དགེ་འདུན་གྲུབ་པ།
statistics: null
quality: null
bases:
  I1KG15201:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15201
      total_pages: 836
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG15201.txt
    legacy_id: v001
  I1KG15202:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15202
      total_pages: 854
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG15202.txt
    legacy_id: v002
  I1KG15205:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15205
      total_pages: 642
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG15205.txt
    legacy_id: v005
  I1KG15209:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15209
      total_pages: 690
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I1KG15209.txt
    legacy_id: v009
  I1KG15206:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15206
      total_pages: 364
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1KG15206.txt
    legacy_id: v006
  I1KG15203:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15203
      total_pages: 624
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG15203.txt
    legacy_id: v003
  I1KG15207:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15207
      total_pages: 530
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I1KG15207.txt
    legacy_id: v007
  I1KG15204:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15204
      total_pages: 544
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG15204.txt
    legacy_id: v004
  I1KG15208:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15208
      total_pages: 436
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I1KG15208.txt
    legacy_id: v008
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
