id: I384896EB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-12T14:28:54+00:00'
last_modified: '2022-06-15T15:22:51.806280+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14505
  title: གསུང་འབུམ། དགེ་འདུན་གྲུབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3C0C:
      image_group_id: I1KG15201
      title: Volume 1 of gsung 'bum/_dge 'dun grub/
      total_pages: 836
      order: 1
      base_file: 3C0C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
